const FALLBACK_PATHS={sports:'./data/fallback/sports.json',youtube:'./data/fallback/youtube.json',reddit:'./data/fallback/reddit.json'};
const state={sports:[],youtube:[],reddit:{hot:[],new:[]},redditSort:'hot',weather:null};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const weatherCodes={0:['Clear sky','☼'],1:['Mainly clear','◒'],2:['Partly cloudy','◐'],3:['Overcast','☁'],45:['Foggy','≋'],48:['Rime fog','≋'],51:['Light drizzle','⋰'],53:['Drizzle','⋰'],55:['Heavy drizzle','⋰'],61:['Light rain','☂'],63:['Rain','☂'],65:['Heavy rain','☂'],71:['Light snow','❄'],73:['Snow','❄'],75:['Heavy snow','❄'],80:['Rain showers','☂'],81:['Rain showers','☂'],82:['Heavy showers','☂'],95:['Thunderstorm','ϟ'],96:['Thunderstorm','ϟ'],99:['Thunderstorm','ϟ']};
const defaultLocation={name:'Buffalo, NY',latitude:42.8864,longitude:-78.8784};
const weatherInfo=code=>weatherCodes[code]||['Conditions unknown','·'];
const escapeHtml=(value='')=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function relativeTime(iso){const diff=Math.max(0,Date.now()-new Date(iso).getTime()),m=Math.floor(diff/60000);if(m<1)return'just now';if(m<60)return`${m}m ago`;const h=Math.floor(m/60);if(h<24)return`${h}h ago`;return`${Math.floor(h/24)}d ago`}
function formatHour(time){const h=Number(time.split('T')[1]?.slice(0,2)||0);return`${h%12||12}${h>=12?'p':'a'}`}
function formatDate(date,options={weekday:'short',month:'short',day:'numeric'}){return new Date(`${date}T12:00:00Z`).toLocaleDateString(undefined,{...options,timeZone:'UTC'})}
function formatGameDate(iso){return new Date(iso).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
function formatGameTime(iso){return new Date(iso).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}
function setText(selector,value){const node=$(selector);if(node)node.textContent=value}
const teamBadgeNames={BUF:'buf',NYJ:'nyj',ATL:'atl',MIA:'mia',NJD:'njd',NYR:'nyr',UGA:'uga',AUB:'aub'};
function teamBadge(abbr){const clean=String(abbr||'').toUpperCase();return`<span class="team-badge ${teamBadgeNames[clean]||'generic'}" aria-hidden="true">${escapeHtml(clean.slice(0,4))}</span>`}
async function fetchJson(path,fallbackPath=path){try{const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error(`${response.status}`);return await response.json()}catch(error){const fallback=await fetch(fallbackPath).then(response=>response.json());return{...fallback,stale:true,error:`Live data unavailable (${error.message})`}}}
function updateClock(){const now=new Date();setText('#clock-label',now.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'}));setText('#today-label',now.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}).toUpperCase())}
function saveLocation(location){localStorage.setItem('daymark-location',JSON.stringify(location));return location}
function readLocation(){try{return JSON.parse(localStorage.getItem('daymark-location'))||defaultLocation}catch{return defaultLocation}}
async function geocode(query){const response=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(query)}&count=1&language=en&format=json`);if(!response.ok)throw new Error('Location search failed');const result=(await response.json()).results?.[0];if(!result)throw new Error('No matching location found');return{name:[result.name,result.admin1,result.country_code].filter(Boolean).slice(0,2).join(', '),latitude:result.latitude,longitude:result.longitude}}
async function requestCurrentLocation(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Geolocation is not available in this browser'));navigator.geolocation.getCurrentPosition(async({coords})=>{try{const result=(await fetch(`https://geocoding-api.open-meteo.com/v1/reverse?latitude=${coords.latitude}&longitude=${coords.longitude}&count=1&language=en&format=json`).then(response=>response.json())).results?.[0];resolve({name:[result?.name,result?.admin1].filter(Boolean).join(', ')||'Current location',latitude:coords.latitude,longitude:coords.longitude})}catch{resolve({name:'Current location',latitude:coords.latitude,longitude:coords.longitude})}},()=>reject(new Error('Location permission was not granted')),{enableHighAccuracy:false,timeout:9000})})}
async function loadWeather(location=readLocation()){setText('#weather-location-label',location.name.toUpperCase());try{const params=new URLSearchParams({latitude:location.latitude,longitude:location.longitude,current:'temperature_2m,apparent_temperature,weather_code,wind_speed_10m,precipitation',hourly:'temperature_2m,apparent_temperature,precipitation_probability,weather_code,wind_speed_10m',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max',forecast_days:'5',temperature_unit:'fahrenheit',wind_speed_unit:'mph',precipitation_unit:'inch',timezone:'auto'});const response=await fetch(`https://api.open-meteo.com/v1/forecast?${params}`);if(!response.ok)throw new Error('Weather service unavailable');const data=await response.json();state.weather={...data,location};renderWeather(data,location)}catch{const fallback=await fetch('./data/fallback/weather.json').then(response=>response.json());state.weather={...fallback,location};renderWeather(fallback,location,true);setText('#weather-note','Live weather is unavailable; showing a sample brief.')}}
function renderWeather(data,location,stale=false){const current=data.current,[description,icon]=weatherInfo(current.weather_code);setText('#weather-location-label',location.name.toUpperCase());setText('#weather-icon',icon);setText('#weather-summary',description);setText('#current-temperature',Math.round(current.temperature_2m));setText('#feels-like',`${Math.round(current.apparent_temperature)}°`);setText('#wind-speed',`${Math.round(current.wind_speed_10m)} mph`);setText('#rain-chance',`${Math.round(data.hourly?.precipitation_probability?.[0]||0)}%`);setText('#forecast-timezone',data.timezone?.replace('_',' ')||'LOCAL TIME');let start=data.hourly.time.findIndex(time=>time>=current.time);if(start<0)start=0;$('#hourly-row').innerHTML=data.hourly.time.slice(start,start+6).map((time,index)=>{const sourceIndex=data.hourly.time.indexOf(time),info=weatherInfo(data.hourly.weather_code[sourceIndex]);return`<div class="hour-card ${index===0?'current':''}"><span class="hour-time">${index===0?'NOW':formatHour(time)}</span><span class="hour-icon">${info[1]}</span><span class="hour-temp">${Math.round(data.hourly.temperature_2m[sourceIndex])}°</span><span class="hour-rain">${data.hourly.precipitation_probability[sourceIndex]||0}% rain</span></div>`}).join('');$('#forecast-row').innerHTML=data.daily.time.map((date,index)=>{const info=weatherInfo(data.daily.weather_code[index]);return`<div class="forecast-card"><span class="forecast-day">${index===0?'TODAY':formatDate(date,{weekday:'short'}).toUpperCase()}</span><span class="forecast-icon">${info[1]}</span><span class="forecast-temp">${Math.round(data.daily.temperature_2m_max[index])}° <small>${Math.round(data.daily.temperature_2m_min[index])}°</small></span><p class="forecast-description">${info[0]} · ${data.daily.precipitation_probability_max[index]||0}% rain</p></div>`}).join('');if(stale)setText('#weather-note','Live weather is unavailable; showing a sample brief.')}
function renderNextUp(){const next=[...state.sports].filter(event=>new Date(event.date)>=new Date(Date.now()-86400000)).sort((a,b)=>new Date(a.date)-new Date(b.date))[0];if(!next){$('#next-up-content').innerHTML='<h3 id="next-up-title">No game on deck.</h3><p class="next-up-meta">Your schedule is quiet for the moment.</p>';return}const isLive=next.status==='in';$('#next-up-content').innerHTML=`<h3 id="next-up-title">${escapeHtml(next.shortName)}</h3><p class="next-up-meta">${isLive?'Live now':`${formatGameDate(next.date)} · ${formatGameTime(next.date)}`}<br />${escapeHtml(next.venue||'Schedule details available')}</p><div class="next-up-score">${next.awayScore!=null?`${next.awayScore} — ${next.homeScore}`:next.league}</div>`}
function gameStatus(event){if(event.status==='in')return'<span class="sport-status live-label">LIVE</span>';if(event.status==='post')return'<span class="sport-status">FINAL</span>';return`<span class="sport-status">${formatGameDate(event.date)}</span>`}
function renderSports(filter='all'){const events=state.sports.filter(event=>filter==='all'||event.league===filter).sort((a,b)=>new Date(a.date)-new Date(b.date));const cards=events.slice(0,8).map(event=>`<article class="sport-card ${event.status==='in'?'live':event.status==='pre'?'next':''}"><span class="sport-league">${escapeHtml(event.league)} / ${escapeHtml(event.team)}</span>${gameStatus(event)}<div class="matchup"><span class="team"><small class="team-abbr">${escapeHtml(event.awayAbbr||'AWAY')}</small>${escapeHtml(event.away)}</span><span class="versus">${event.awayScore!=null?`${event.awayScore}–${event.homeScore}`:'VS'}</span><span class="team"><small class="team-abbr">${escapeHtml(event.homeAbbr||'HOME')}</small>${escapeHtml(event.home)}</span></div><div class="game-time"><b>${event.status==='post'?'Game complete':event.status==='in'?escapeHtml(event.detail||'In progress'):`${formatGameDate(event.date)} · ${formatGameTime(event.date)}`}</b>${escapeHtml(event.venue||'Venue to be announced')}</div></article>`).join('');$('#sports-grid').innerHTML=cards||'<p class="empty-state">No games found for this filter.</p>';const schedule=events.filter(event=>event.status!=='post').slice(0,8).map(event=>`<div class="schedule-item"><div class="schedule-date">${formatGameDate(event.date)}<br />${escapeHtml(event.league)}</div><div class="schedule-match">${escapeHtml(event.shortName)} <small>${escapeHtml(event.team)}</small></div><div class="schedule-meta">${formatGameTime(event.date)}<br />${escapeHtml(event.venue||'TBD')}</div></div>`).join('');$('#schedule-list').innerHTML=schedule||'<p class="empty-state">No upcoming games in the current snapshot.</p>'}
const renderSportsBase=renderSports;
renderSports=function(filter='all'){renderSportsBase(filter);$$('#sports-grid .team').forEach(team=>{const abbr=team.querySelector('.team-abbr')?.textContent?.trim()||'';const name=team.textContent.trim().replace(abbr,'').trim();team.innerHTML=`<span class="team-identity">${teamBadge(abbr)}<span class="team-name"><small class="team-abbr">${escapeHtml(abbr)}</small><span>${escapeHtml(name)}</span></span></span>`})};
function renderTopics(selector,topics){$(selector).innerHTML=(topics||[]).map(topic=>`<span class="topic-pill">${escapeHtml(topic)}</span>`).join('')}
function renderYoutube(data){state.youtube=data.items||[];renderTopics('#youtube-topics',data.topics||['Technology','AI','Cooking','Movement','PlayStation']);$('#youtube-list').innerHTML=state.youtube.slice(0,7).map(item=>`<a class="video-item" href="${escapeHtml(item.url)}" target="_blank" rel="noreferrer"><span class="video-thumb ${item.thumbnail?'':'placeholder'}">${item.thumbnail?`<img class="video-thumb" src="${escapeHtml(item.thumbnail)}" alt="" loading="lazy" />`:'▶'}</span><span><span class="video-topic">${escapeHtml(item.topic||'RECOMMENDED')}</span><span class="video-title">${escapeHtml(item.title)}</span><span class="video-meta">${escapeHtml(item.channel||'YouTube')} · ${item.publishedAt?relativeTime(item.publishedAt):'recent'}</span></span></a>`).join('')||'<p class="empty-state">No video snapshot yet.</p>'}
function renderReddit(data){state.reddit={hot:data.hot||[],new:data.new||[]};renderTopics('#reddit-topics',data.topics||['Tech','AI','Cooking','Movement','PlayStation','Teams']);const items=state.reddit[state.redditSort]||[];$('#reddit-list').innerHTML=items.slice(0,8).map(item=>`<a class="reddit-item" href="${escapeHtml(item.url)}" target="_blank" rel="noreferrer"><span class="reddit-item-top"><span class="reddit-source">r/${escapeHtml(item.subreddit)}</span><span>${item.createdAt?relativeTime(item.createdAt):'recent'}</span></span><span class="reddit-title">${escapeHtml(item.title)}</span><span class="reddit-meta">${item.score??0} points · ${item.comments??0} comments</span></a>`).join('')||'<p class="empty-state">No community snapshot yet.</p>'}
async function loadFeeds(){const[sports,youtube,reddit]=await Promise.all([fetchJson('./data/sports.json',FALLBACK_PATHS.sports),fetchJson('./data/youtube.json',FALLBACK_PATHS.youtube),fetchJson('./data/reddit.json',FALLBACK_PATHS.reddit)]);state.sports=sports.items||[];renderNextUp();renderSports();renderYoutube(youtube);renderReddit(reddit);const stale=[sports,youtube,reddit].some(data=>data.stale);setText('#brief-status',stale?'Using the latest available snapshot':'All signals are current');setText('#updated-label',`Updated ${relativeTime(sports.generatedAt||new Date().toISOString())}`);setText('#footer-status',stale?'Some feeds are showing their latest saved snapshot':'Feeds refreshed successfully')}
function openLocationDialog(){const dialog=$('#location-dialog');if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','')}
function closeLocationDialog(){$('#location-dialog').close?.()}
function setupLocation(){$('#location-button').addEventListener('click',openLocationDialog);$('#use-location-button').addEventListener('click',async()=>{$('#location-error').textContent='Finding you…';try{const location=saveLocation(await requestCurrentLocation());await loadWeather(location);closeLocationDialog()}catch(error){$('#location-error').textContent=error.message}});$('#location-form').addEventListener('submit',async event=>{event.preventDefault();const query=$('#location-input').value.trim();if(!query)return;$('#location-error').textContent='Searching…';try{const location=saveLocation(await geocode(query));await loadWeather(location);closeLocationDialog();$('#location-input').value=''}catch(error){$('#location-error').textContent=error.message}})}
function setupFilters(){$$('#sports-filters button').forEach(button=>button.addEventListener('click',()=>{$$('#sports-filters button').forEach(item=>item.classList.toggle('active',item===button));renderSports(button.dataset.sportFilter)}));$$('.feed-tab').forEach(button=>button.addEventListener('click',()=>{state.redditSort=button.dataset.redditSort;$$('.feed-tab').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-selected',active)});renderReddit(state.reddit)}))}
async function init(){updateClock();setInterval(updateClock,30000);setupLocation();setupFilters();$('#refresh-button').addEventListener('click',async()=>{$('#refresh-button').classList.add('spinning');await Promise.all([loadWeather(readLocation()),loadFeeds()]);$('#refresh-button').classList.remove('spinning')});await Promise.all([loadWeather(readLocation()),loadFeeds()]);if(!localStorage.getItem('daymark-geo-asked')&&!localStorage.getItem('daymark-location')){localStorage.setItem('daymark-geo-asked','true');requestCurrentLocation().then(location=>{saveLocation(location);loadWeather(location)}).catch(()=>{})}}
init();
